version: '3'
services: 
    mongo:
        container_name: mongo_container
        image: mongo:3
        restart: always
        volumes: 
            - ./data:/data/db
        ports: 
            - 27017:27017
    backend:
        container_name: backend_container
        build: .
        image: mp-backend
        restart: always
        command: npm run debug
        volumes: 
            - ./dist:/usr/src/mp-back/dist
            - ./package.json:/usr/src/mp-back/package.json
            - ./package-lock.json:/usr/src/mp-back/package-lock.json
        ports: 
            - 5050:5050
            - 9222:9222
        links: 
            - mongo